apiVersion: v1
kind: Template
metadata:
  name: "${APPLICATION_NAME}"
  annotations:
    description: wordpress ImageStream
    tags: wordpress, ImageStream
  labels:
    template: "${APPLICATION_NAME}" 
objects:
  - 
    kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${APPLICATION_NAME}-img'
      labels:
        app: '${APPLICATION_NAME}'
    spec: {}

parameters:
  - name: APPLICATION_NAME
    description: The name of the WordPress Application.
    value: my-wordpress-site
    from: '[a-zA-Z0-9]'
    required: true
