---
apiVersion: v1
kind: Template
metadata:
  name: "${APPLICATION_NAME}"
  annotations:
    description: wordpress service
    tags: wordpress,service
  labels:
    template: "${APPLICATION_NAME}" 
objects:
- apiVersion: v1
  kind: Service
  metadata:
   name: "${APPLICATION_NAME}"
   labels:
     app: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
parameters:
 - name: APPLICATION_NAME
   description: The name of the WordPress instance.
   value: my-wordpress-site
   from: '[a-zA-Z0-9]'
   required: true
