kind: Template
apiVersion: template.openshift.io/v1
metadata:
    name: 'wordpress-migration-template'
    annotations:
        description: The template of wordpress migration.
        tags: 'wordpress,buildconfig, template'
        iconClass: "icon-wordpress"
    labels: 
        template: "wordpress-migration-template"
objects:
- 
  apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wordpress-build-pipeline
  spec:
    failedBuildsHistoryLimit: 3
    successfulBuildsHistoryLimit: 3
    runPolicy: Serial
    source:
      contextDir: 
      git:
        ref: master
        uri: 'https://git@github.com:/sculang/demo-wp.git'
      sourceSecret:
        name: my-github-secret
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline/wordpress-build-pipeline.groovy
        env:
          - name: BRANCH
            value: master
          - name: SOURCES_URL
            value: 'https://git@github.com:/sculang/demo-wp.git'
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
          - name: GIT_CREDENTIALS
            value: scu-wordpress-my-github-token            
      type: JenkinsPipeline
    triggers: []

- 
  apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wordpress-deploy-pipeline
  spec:
    failedBuildsHistoryLimit: 3
    successfulBuildsHistoryLimit: 3
    runPolicy: Serial
    source:
      contextDir: 
      git:
        ref: master
        uri: 'https://git@github.com:/sculang/demo-wp.git'
      sourceSecret:
        name: my-github-secret
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipeline/wordpress-deploy-pipeline.groovy
        env:
          - name: BRANCH
            value: master
          - name: SOURCES_URL
            value: 'https://git@github.com:/sculang/demo-wp.git'
          - name: GIT_CREDENTIALS
            value: scu-wordpress-my-github-token                
          - name: DEPLOY_PROJECT
            value: ${DEPLOY_PROJECT}
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
          - name: DB_NAME
            value: ${DB_NAME}
          - name: APP_HOST
            value: ${APP_HOST}
          - name: ZIP_LINK_WP
            value: ${ZIP_LINK_WP}
          - name: ZIP_LINK_SQL
            value: ${ZIP_LINK_SQL}
          - name: OLD_URL
            value: ${OLD_URL}
      type: JenkinsPipeline
    triggers: []

parameters:
- name: APPLICATION_NAME
  description: The name of the WordPress instance.
  value: my-wordpress-site
  from: "[a-zA-Z0-9]"
  required: true
- name: DB_NAME
  description: The name of the mysql instance.
  value: my-wordpress-site-db
  from: "[a-zA-Z0-9]"
  required: true
- name: DEPLOY_PROJECT
  description: The name of the project to deploy the website.
  value: wordpress-migration-test
  from: "[a-zA-Z0-9]"
  required: true
- name: APP_HOST
  description: Enter your application name
  value: my-wordpress-site
  from: "[a-zA-Z0-9]"
  required: false
- name: ZIP_LINK_WP
  description: The link of wordpress website content.
  value: 
  from: "[a-zA-Z0-9]"
  required: true
- name: ZIP_LINK_SQL
  description: The link of SQL dump.
  value: 
  from: "[a-zA-Z0-9]"
  required: true
- name: OLD_URL
  description: link of your old URL
  value: 
  required: true

