---
kind: Template
apiVersion: v1
metadata:
    name: '${APPLICATION_NAME}-secret'
    annotations:
        description: wordpress secret
        tags: 'wordpress,secret'
    labels:
        template: "${APPLICATION_NAME}-secret"
objects:
  - 
    apiVersion: v1
    kind: Secret
    metadata:
      name: "${APPLICATION_NAME}-mysql-secret"
      labels:
        app: ${APPLICATION_NAME}
    stringData:
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
parameters:
-
  description: The name of the database user.
  name: DATABASE_USERNAME
  from: user[a-f0-9]{8}
  generate: expression
-
  description: The password for the database user.
  name: DATABASE_PASSWORD
  from: "[a-zA-Z0-9]{12}"
  generate: expression
- 
  name: APPLICATION_NAME
  description: "The name of the WordPress instance."
  value: my-wordpress-site
  from: "[a-zA-Z0-9]"
  required: true
